config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/', to: 'welcome#index'

  get '/directors', to: 'directors#index'
  post '/directors', to: 'directors#create'
  get '/directors/new', to: 'directors#new'
  get '/directors/:id/edit', to: 'directors#edit'
  get '/directors/:id', to: 'directors#show'
  patch '/directors/:id', to: 'directors#update'
  
  get '/films', to: 'films#index'
  patch '/films/:id', to: 'films#update'
  post '/films', to: 'films#create'
  get '/films/:id/edit', to:'films#edit'
  get '/films/new', to: 'films#new'
  get '/films/:id', to: 'films#show'
  
  get '/directors/:id/films', to: 'director_films#index'
  post '/directors/:id/films', to: 'director_films#create'
  get '/directors/:id/films/new', to: 'director_films#new'
  get '/directors/:id/films/edit', to: 'director_films#edit'
  get '/directors/:id/films/:id', to: 'director_films#show'
  patch '/directors/:id/films/:id', to: 'director_films#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/director.rb
class Director < ApplicationRecord
  has_many :films
  validates_presence_of :name
  validates_numericality_of :best_director_oscars
  validates :multiple_best_director_nominations, inclusion: [true, false]
  
  def self.last_created
    order(created_at: :desc)
  end

  def film_count
    films.count
  end

  def ordered_alphabetical
    films.order(:name)
  end 
end

app/models/film.rb
class Film < ApplicationRecord
  belongs_to :director

  validates_presence_of :name
  validates_numericality_of :release_year
  validates :best_picture_oscar, inclusion: [true, false]

  def self.oscar_winners
    where(best_picture_oscar: :true)
  end

  def self.alphabetical_order 
    order(name: :asc)
  end

  # def ordered_alphabetical
  #   films.order(:name)
  # end

  # def ordered_alpha
  #   # self.order(:name)
  #   where(director: :self).order(:name)
  #   require 'pry';binding.pry
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/director_films_controller.rb
class DirectorFilmsController < ApplicationController
  def index
    @director = Director.find(params[:id])
    
    if params[:sort] == 'true'
      @films = @director.ordered_alphabetical
    else
      @films = @director.films.all
    end
  end

  def new
    @director = Director.find(params[:id])
    @film = @director.films.new
  end

  def create
    @director = Director.find(params[:id])
    @film = @director.films.create(director_film_params)
    if @film.save 
      flash.notice = "Update Successful"
      redirect_to "/directors/#{@director.id}/films"
    else
      flash.notice = "Unacceptable Entry - Try Again"
      render :new
    end
  end

  private
  def director_film_params
    params.permit(:name,:release_year,:best_picture_oscar)
  end
end

app/controllers/directors_controller.rb
class DirectorsController < ApplicationController
  def index
    @directors = Director.all.last_created
  end

  def show
    @director = Director.find(params[:id])
  end
  
  def create
    @director = Director.create(director_params)
    if @director.save 
      flash.notice = "Update Successful"
      redirect_to directors_path
    else
      flash.notice = "Unacceptable Entry - Try Again"
      render :new
    end
  end
  # flash message hide elemtent  https://bobbyhadz.com/blog/javascript-hide-element-after-few-seconds

  def new
    # require 'pry';binding.pry!!
    # @director = Director.find(params[:id])
    @director = Director.new
    # rendirect_to :create
  end

  def edit
    @director = Director.find(params[:id])
    # require 'pry';binding.pry
  end
  
  def update
    @director = Director.find(params[:id])
    @director.update!(director_params)

    flash.notice = "Update Successful"
    redirect_to "/directors/#{@director.id}"
    # ISSUE:
      #  when user goes show>edit>update/show>edit> 
      #radio button for previous result not displaying consistently
  end

  private
  def director_params
    params.permit(:name,:best_director_oscars,:multiple_best_director_nominations)
  end
end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  def index
    @films = Film.oscar_winners
  end

  def show
    @film = Film.find(params[:id])
  end


  def new
    # require 'pry';binding.pry
    @directors = Director.all
    @film = Film.new
  end
  
  def create
    # require 'pry';binding.pry
    
    # @directors = Director.all
    @film = Film.create(film_params)
    if @film.save 
      flash.notice = "Update Successful"
      redirect_to films_path
    else
      flash.notice = "Unacceptable Entry - Try Again"
      render :new
    end
  end
  # flash message hide elemtent  https://bobbyhadz.com/blog/javascript-hide-element-after-few-seconds

  def edit
    @film = Film.find(params[:id])
  end
  
  def update
    @film = Film.find(params[:id])
    @film.update!(film_params)
# require 'pry';binding.pry
    flash.notice = "Update Successful"
    redirect_to "/films/#{@film.id}"
  end

  private
  
  def film_params
    params.permit(:name,:release_year,:best_picture_oscar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/director_films/_form.html.erb
<%= form_with url: path, method: method, local: true do |f| %>
  <ul><%= f.label :name, "Name" %>
  <%= f.text_field :name, value: @film.name %></ul>
  
  <ul><%= f.label :release_year, "Release Year", value: @film.release_year %>
  <%= f.select :release_year, (1878..Time.now.year).to_a,  {:release_year => "Select year"} %></ul>

  <ul><%= f.label :best_picture_oscar, "Best Picture Oscar?", value: @film.best_picture_oscar %>
    <ol><%= f.radio_button :best_picture_oscar, value=false, { checked: @film.best_picture_oscar} %> Check if False</ol>
    <ol><%= f.radio_button :best_picture_oscar, value=true, { checked: @film.best_picture_oscar} %> Check if True </ol></ul>
  
  <%= f.submit button_text %>  
<% end %>

app/views/director_films/index.html.erb
<center><h1 style="color: RoyalBlue"><%= @director.name %> Films</h1></center>

<% @films.each do |film| %>
  <div id="director-film-attributes-<%=film.id %>">
    <h3 style="color: FireBrick"><%= film.name %></h3>
    <ul>Release Year <%= film.release_year %>, Best Picture Oscar Winner? <%= film.best_picture_oscar%></ul>
    <ul>Entry Created (dd/mm/yyyy): <%= film.created_at.strftime("%d/%m/%Y") %>, Entry Last Updated (dd/mm/yyyy): <%= film.updated_at.strftime("%d/%m/%Y")%></ul>
    <ul><%= link_to "Update Film #{film.name}", "/films/#{film.id}/edit" %></ul>
  </div>
<% end %>

<div style="position:fixed; padding: 1em; bottom:0; right: 0;">
  <i><%= link_to "Sort Films A to Z", "/directors/#{@director.id}/films?sort=true" %></i>
  <i><%= link_to 'Create New Film', "/directors/#{@director.id}/films/new" %></i>
</div>

app/views/director_films/new.html.erb
<center><h1>New Film</h1></center>

<%= render partial: 'form', locals: {
                                    path: "/directors/#{@director.id}/films",
                                    method: :post,
                                    name: @film.name,
                                    release_year: @film.release_year,
                                    best_picture_oscar: @film.best_picture_oscar,
                                    button_text: "Add film"} %>
        

app/views/directors/edit.html.erb
<center><h1 style="color: Blue; padding: .5em"> Edit <%= @director.name %></h1></center>

<%= form_with url: "/directors/#{@director.id}", method: :patch, local: true do |form|%>
  
  <p><%= form.label :name, "Name" %>
  <%= form.text_field :name, value: @director.name %></p>

  <%= form.label :best_director_oscars, "Number of Best Director Oscars"  %>
  <%= form.number_field :best_director_oscars, value: @director.best_director_oscars, min: 0 %></p>

  <p><%= form.label :multiple_best_director_nominations, "Has Multiple Best Director Nominations?" %> &nbsp <strong></p>
  
  <p><%= form.radio_button :multiple_best_director_nominations, value=false, { checked: !@director.multiple_best_director_nominations } %> Check if False
  <%= form.radio_button :multiple_best_director_nominations, value=true, { checked: @director.multiple_best_director_nominations }  %> Check if True </p>
  
  <%= form.submit 'Update Director'%>

<% end %>

app/views/directors/index.html.erb
<h1 style="color: navy"><center>Directors<center></h1>

<% @directors.each do |director| %>
  <div id="director-links-<%= director.id %>">
    <p><strong><%= link_to director.name, "/directors/#{director.id}"  %></strong>
    <ul><%= link_to "Update Director #{director.name}", "/directors/#{director.id}/edit" %></ul></p>
  </div>
  <br>
<% end %>

<div style="position:fixed; padding: 1em; bottom:0; right: 0;">
  <i><%= link_to 'Create New Director', directors_new_path %></i>
</div>

<head>
<style>
  body {
    background-image: url('https://c7.alamy.com/comp/2F3WHMW/retro-photocamera-film-making-machine-cinematography-cam-isolated-monochrome-icon-vector-old-film-projector-camera-with-reels-movie-making-instru-2F3WHMW.jpg');
    background-repeat: no-repeat;
    background-attachment: fixed; 
    background-right: 0; 
    background-size:75% 130%;
  }
</style>
</head>

app/views/directors/new.html.erb
<h1>New Director</h1></center>

<%= form_with url: directors_path, method: :post, local: true do |form|%>
  <p><%= form.label :name, "Name" %>
  <%= form.text_field :name, value: @director.name %></p>

  <%= form.label :best_director_oscars, "Number of Best Director Oscars" %>
  <%= form.number_field :best_director_oscars, value: @director.best_director_oscars, min: 0 %></p>

  <p><%= form.label :multiple_best_director_nominations, "Has Multiple Best Director Nominations?", 
  value: @director.multiple_best_director_nominations %>
  <ul><%= form.radio_button :multiple_best_director_nominations, value=false %> Check if False</ul>
  <ul><%= form.radio_button :multiple_best_director_nominations, value=true %> Check if True </ul></p>
  
  <%= form.submit 'Add Director'%>
<% end %>

app/views/directors/show.html.erb
<center><h1 style="color: MidnightBlue; padding: .5em"><%= @director.name %></h1></center>
<p><h3> Number of Films: <%= @director.film_count %></h3></p>
<p><h3> Number of Best Director Oscars: <%= @director.best_director_oscars %></h3></p>
<p><h3> Has Multiple Best Director Nominations? <%= @director.multiple_best_director_nominations%></h3></p>
<p><h3><%= link_to 'Film Catalogue', "/directors/#{@director.id}/films" %></h3></p>

<div style="position:fixed; padding: 1em; bottom:0; right: 0;">
  <i><%= link_to 'Update Director', "#{@director.id}/edit" %></i>
</div>

app/views/films/edit.html.erb
<center><h1 style="color: Tomato; padding: .5em"> Edit <%= @film.name %></h1></center>

<%= form_with url: "/films/#{@film.id}", method: :patch, local: true do |f|%>
  <ul><%= f.label :name, "Name" %>
    <%= f.text_field :name, value: @film.name %></ul>
  
  <ul><%= f.label :release_year, "Release Year", value: @film.release_year %>
    <%= f.select :release_year, (1878..Time.now.year).to_a,  {:value => @film.release_year}  %></ul>

  <ul><%= f.label :best_picture_oscar, "Best Picture Oscar?", value: @film.best_picture_oscar %>
    <ol><%= f.radio_button :best_picture_oscar, value=false, { checked: !@film.best_picture_oscar} %> Check if False</ol>
    <ol><%= f.radio_button :best_picture_oscar, value=true, { checked: @film.best_picture_oscar} %> Check if True </ol></ul>
  
  <%= f.submit "Update Film" %>  
<% end %>

app/views/films/index.html.erb
<h1 style="color: Maroon"><center>Films<center></h1>

<% @films.each do |film| %>
  <div id="film-attributes-<%=film.id %>">
    <h3><%= link_to film.name, "/films/#{film.id}" %></h3>
    <ul>Director: <%= film.director.name %>, Release Year <%= film.release_year %>, Best Picture Oscar Winner? <%= film.best_picture_oscar%></ul>
    <ul>Entry Created (dd/mm/yyyy): <%= film.created_at.strftime("%d/%m/%Y") %>, Entry Last Updated (dd/mm/yyyy): <%= film.updated_at.strftime("%d/%m/%Y")%></ul>
   <ul><%= link_to "Update Film #{film.name}", "/films/#{film.id}/edit" %></ul></p>
  </div>
<% end %>

app/views/films/show.html.erb
<h1 style="color: DarkRed"><center><%= @film.name %><center></h1>
<p><h3>Release Year: <%= @film.release_year%></h3></p>
<p><h3>Won Best Picture Oscar? <%= @film.best_picture_oscar%></h3></p> 
<p><h3>Director: <%= link_to @film.director.name, "/directors/#{@film.director.id}" %></h3></p>

<div style="position:fixed; padding: 1em; bottom:0; right: 0;">
  <i><%= link_to 'Update Film', "#{@film.id}/edit" %></i>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelationalRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <div style="position:fixed; padding: 1em; top: 0; right: 0;">
      <i><%= link_to 'Directors', directors_path %>
      <%= link_to 'Films', films_path %>
      <%= link_to 'Main', "/" %></i>
    </div>

    <% flash.each do |type, message| %>
      <div>
        <h3 style="color: Red"><%= message %></h3>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/welcome/index.html.erb
<head>
<style>
body {
  background-image: url('http://img-aws.ehowcdn.com/1280x/www.onlyinyourstate.com/wp-content/uploads/2016/04/o-10-40.jpg');
  background-repeat: no-repeat;
  background-attachment: fixed; 
  background-size: 100% 100%;
}
</style>
</head>

<header><u><h1 style="color:Black;"><center>The Motion-Picture</center></h1></u></header>